### ISSUE TITLE
Backorder not working for 0 stock

### ISSUE THREAD

**Issue by in2computing** [husseycoding/backorder#5] opened 2015-06-12 06:18 UTC
Hi 

I am using your Backorder Magento extension. It is working great when I order more than available stock but it doesnt when stock is 0. Can you please help me to solve this issue? 

Looking forward to hear from you.

Regards
Yogi

**Comment by husseycoding** [comment] 2015-06-12 08:36
It's not actually totally clear on where the issue lies.  If a product has zero stock it will be marked as out of stock unless backorders are allowed, so is the issue that things are not working when backorders are allowed and the product stock is zero?  Can you describe what the actual issue is, i.e. what are you seeing compared to what are you expecting to see?

**Comment by in2computing** [comment] 2015-06-12 09:06
Hi
I have made below videos to explain the issue and the settings for inventory and backorder extension settings. I hope this helps.
Issue - http://screencast-o-matic.com/watch/co1ljLfbuS
Settings - http://screencast-o-matic.com/watch/co1lQefbUh

**Comment by husseycoding** [comment] 2015-06-12 09:18
Thanks for the video, I'm not really clear on why you think the issue is with the extension, I'm seeing a 404 error which I don't believe can be caused by the extension - it doesn't do anything with the standard Magento routing at all.

Can you explain how you have narrowed down the issue to being with the extension rather than something else?

**Comment by husseycoding** [comment] 2015-06-15 04:22
Closing this one as with the current information it doesn't appear to be an issue with the extension.  Just re-open if you have anything more to add.

**Closed as completed by husseycoding** 2015-06-15 04:22 UTC
Labels: invalid

**Comment by in2computing** [comment] 2015-06-15 06:13
My apologies... I found the problem... It was nothing to do with your extension... there was some issues with a few child products... I deleted and recreated them and all is fine now...

**Comment by husseycoding** [comment] 2015-06-15 07:52
No problems, thanks for the update and glad you got the issue sorted.
